### ISSUE TITLE
Heroic Strike DestinyActivityModeType

### ISSUE THREAD

**Issue by mattybeard** [Bungie-net/api#334]
Normal strikes and heroic strikes both return the following for their ActivityModeType
3,7,18

Should there be a different activity mode type for heroic strikes? There is a split for Nightfall.

**Comment by vthornheart-bng** [comment]
Hmm, a good question.  I will have to check on whether we can provide this!

**Comment by cortical-iv** [comment]
Just following up on this: is there some sneaky way I'm missing to find # completed heroic nightfalls? When I enter mode 16 for GetHistoricalStats (heroicNightfall mode) it comes back empty.

**Comment by floatingatoll** [comment]
One sneaky option: If the player has an emblem in their inventory with the correct kind of nightfall counter attached to it (I don’t know if there is one or not), you can inspect the emblem using Item calls to get the count directly rather than using Activity APIs.

**Comment by cortical-iv** [comment]
Now *that* is sneaky.

**Comment by cortical-iv** [comment]
Someone over at Discord pointed out that GetActivityHIstory will return the individual events (mode 16=nightfall, and 17=prestige), though you have to cycle through the data to compile stats that you woudl normally just pull from GetHistoricalStats. It would be really awesome to have that provide in GetHistoricalStats someday

**Comment by vthornheart-bng** [comment]
This should be fixed as part of Tetron's fixes I believe - the miscategorization of heroic strikes was due to some issues that should be resolved shortly!

**Comment by mattybeard** [comment]
@vthornheart-bng This still appears to be an issue and we are unable to tell a heroic strike from a normal strike.

**Comment by vthornheart-bng** [comment]
For new Heroic Nightfalls?  Or for ones from before the fix?

**Comment by mattybeard** [comment]
Whenever I run a heroic strike of any sort, it's returns as a "normal strike" when it definitely wasn't.

Giving you an example: https://www.bungie.net/en/PGCR/1531983355 - this was a heroic strike.

**Comment by vthornheart-bng** [comment]
Ah, interesting!  Good stuff, thanks - I'll take a look!

**Comment by vthornheart-bng** [comment]
Yep, sure enough.  Damn!  Thanks for reporting it, I'm not sure how we missed that.  I'll talk to some folks now.  My apologies for the ongoing troubles!

**Comment by TorKallon** [comment]
If you start returning a new mode for heroic strikes, please give us a heads-up what the number will be here. Our workaround for this is completely fine and if those strikes start showing up with a new mode that we have not seen before it’ll break our code.

**Comment by mattybeard** [comment]
@TorKallon How are you working around it?

**Comment by rentalhost** [comment]
Some update about that?

There are some workaround to identify if an activity is heroic/prestige via API response or maybe using the Manifest content?
