### ISSUE TITLE
Public Milestones reports wrong end dates for 4 day reset items

### ISSUE THREAD

**Issue by dcaslin** [Bungie-net/api#648]
https://www.bungie.net/Platform/Destiny2/Milestones/

As of 9/5 the flashpoint shows as: 

```
"463010297": {
            "milestoneHash": 463010297,
            "availableQuests": [
                {
                    "questItemHash": 2332272114
                }
            ],
            "startDate": "2018-09-04T17:00:01Z",
            "endDate": "2018-09-11T17:00:01Z",
            "order": 500
        }
```

I believe the 2018-09-11 endDate should be something more like 2018-09-08

**Comment by vthornheart-bng** [comment]
Ah, good question - I need to investigate that for sure.  I'll loop back on this shortly.

**Comment by floatingatoll** [comment]
Additionally, that 7-day window contains an extra clock second at the
terminus, causing the final second of a window to overlap with the
first second of the following window. This is more apparent when two
are seen in a row:

            "startDate": "2018-09-04T17:00:01Z",
            "endDate": "2018-09-11T17:00:01Z",

            "startDate": "2018-09-11T17:00:01Z",
            "endDate": "2018-09-18T17:00:01Z",

Which window is 2018-09-11T17:00:01Z in, the first or the second?

**Comment by vthornheart-bng** [comment]
TFS: 707011

**Comment by vthornheart-bng** [comment]
Okay, I did some investigating - and I fixed a bug causing the 1 second time miscalculation.  However, the date ranges are going to continue to overlap as such: end date is exclusive, and startDate is inclusive.  So the very instant that it rolls over to 17:00:00, the last endDate is over and the new startDate begins.

I did some further investigating on when the end/start dates should be, and after a bit of digging I found out that indeed these date ranges (once the 1 second error is fixed) will be correct: the flashpoint is on a single 7 day cycle.

There appears to be a game-side bug where you can theoretically still have last week's flashpoint in some scenarios, but I believe that is being looked into on the game side: and if you try to do the prior week's flashpoint during the current week, you will not get a reward for it.  So heads up on that in case you got into that situation and you were hoping to do both!

**Comment by ttgmpsn** [comment]
Maybe you already fixed this when you got the 1-second-bug, but right now the date ranges for 4-day-reset items (daily milestones) are still wrong. For me, the API currently reports as Daily Milestones (description, startDate, endDate):

`{'description': 'Complete a Crucible match.', 'name': 'Daily Crucible Challenge', 'icon': '/img/destiny_content/milestones/icons/quickplay.png', 'hasIcon': True}
2018-09-07T17:00:00Z
2018-09-11T17:00:00Z
{'description': 'Complete a strike.', 'name': 'Daily Vanguard Strike', 'icon': '/img/destiny_content/milestones/icons/vanguard_strikes.png', 'hasIcon': True}
2018-09-09T17:00:00Z
2018-09-13T17:00:00Z
{'description': 'Complete a Gambit match.', 'name': 'Daily Gambit Challenge', 'icon': '/img/destiny_content/milestones/icons/gambit.png', 'hasIcon': True}
2018-09-09T17:00:00Z
2018-09-13T17:00:00Z`

The real daily that started on this reset (2018-09-10 at 17:00 UTC) is Crucible, Strike started on 2018-09-08, Gambit is the only correct one and actually started on 2018-09-09.

**Comment by vthornheart-bng** [comment]
Ah, good find!  Glad you brought this up - I'd not noticed, but indeed we're pointing at the wrong underlying date range data for those.  I'll see if we can get that fixed for the 9/18 release.
