### ISSUE TITLE
Daily Gambit and Heroic Adventures milestones missing rewards

### ISSUE THREAD

**Issue by bhollis** [Bungie-net/api#715]
These milestones should have "Powerful Gear" as their rewards, but they are missing any `DestinyMilestone.rewards` entry.

**Comment by vthornheart-bng** [comment]
Ah - I'll look into this!

**Comment by vthornheart-bng** [comment]
TFS 717462

**Comment by bhollis** [comment]
I think this may have been fixed?

**Comment by vthornheart-bng** [comment]
Oh, yes - I lost track of this.  It should be good now, though we still have a larger problem related to the fact that we don't return different levels of rewards based on the requested characters' level.  I believe that's covered in another bug though, which I'm not certain if or when we'll ever get to.
