### ISSUE TITLE
Aesthetic improvements requested for OAuth sign-in page

### ISSUE THREAD

**Issue by floatingatoll** [Bungie-net/api#87]
This screenshot presents several aesthetic improvements to be made:

1) The app name is ridiculously large.
2) The text "Third-party app login requested by:" is missing between "Bungie.net" and "Ishtar".
3) The left margin of padding is wastes precious mobile screen space
4) The warning text is truncated rather than wrapped
5) The "Approve" button is not shown on the first page in portrait mode.

![fullsizeoutput_221d](https://user-images.githubusercontent.com/92684/30288324-3070ab92-96dd-11e7-8826-c49dccc1e0d3.jpeg)

**Comment by floatingatoll** [comment]
Also, what even *happens* if you hit "Sign out" here, when you're in the midst of an OAuth workflow? We literally just signed in seconds ago (as forced to every time, by design), so I assume it completely shatters the entire process, and appears entirely irrelevant in light of that design choice.

**Comment by hellocontrol-bng** [comment]
That is some giant text. Good catch.

**Comment by Tetron-bng** [comment]
RE: What happens when you sign out. You will be prompted to sign in again. It should not break the whole flow.  This is to help in cases (especially on web) where the browser had been used to signed into  Bungie.net using an account that the current user would rather change.

Other feedback: Great feedback.  Thanks!

**Comment by bhollis** [comment]
I believe this has been fixed?

**Comment by vthornheart-bng** [comment]
To some extent - it's still not looking great, but hopefully a bit better these days!
